version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 10
    labels: ["deps","ci"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:15"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 10
    labels: ["deps","python"]
    versioning-strategy: increase-if-necessary
