name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels: ['feat','feature','enhancement']
  - title: '🐛 Fixes'
    labels: ['fix','bug']
  - title: '🧰 Maintenance'
    labels: ['chore','build','ci','refactor']
  - title: '📝 Docs'
    labels: ['docs']
  - title: '✅ Tests'
    labels: ['test']

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'No changes.'

version-resolver:
  major:
    labels: ['major','breaking','semver:major']
  minor:
    labels: ['minor','feat','enhancement','semver:minor']
  patch:
    labels: ['patch','fix','chore','ci','docs','refactor','test','semver:patch']
  default: patch

template: |
  ## What’s Changed
  $CHANGES
