name: Dependabot
on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Apply labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = new Set(['deps']);
            const sev = process.env.SEVERITY;
            const eco = process.env.PACKAGE_ECOSYSTEM;
            if (eco) labels.add(`deps:${eco}`);
            if (sev) labels.add(`security:${sev.toLowerCase()}`);
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: Array.from(labels)
            });
        env:
          SEVERITY: ${{ steps.meta.outputs.security-advisory-severity }}
          PACKAGE_ECOSYSTEM: ${{ steps.meta.outputs.package-ecosystem }}
