name: dependabot metadata and labels
on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Apply labels
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const sev = core.getInput('severity');
            const ecosys = core.getInput('package-ecosystem');
            const labels = new Set(['deps']);
            if (ecosys) labels.add(`deps:${ecosys}`);
            if (sev) labels.add(`security:${sev.toLowerCase()}`);
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: Array.from(labels)
            });
        env:
          severity: ${{ steps.meta.outputs.security-advisory-severity }}
          package-ecosystem: ${{ steps.meta.outputs.package-ecosystem }}
